<?php

namespace Container0SP7QcW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RT6en1CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rT6en1C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rT6en1C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.usFLA2y', 'get_ServiceLocator_UsFLA2yService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.8C5AXya', 'get_ServiceLocator_8C5AXyaService', true],
            'App\\Controller\\UserController::Add' => ['privates', '.service_locator.tXM58lC', 'get_ServiceLocator_TXM58lCService', true],
            'App\\Controller\\UserController::ShowUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.DNF0f.K', 'get_ServiceLocator_DNF0f_KService', true],
            'App\\Controller\\UserController::deletefront' => ['privates', '.service_locator.DNF0f.K', 'get_ServiceLocator_DNF0f_KService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.3risv2s', 'get_ServiceLocator_3risv2sService', true],
            'App\\Controller\\UserController::editfront' => ['privates', '.service_locator.3risv2s', 'get_ServiceLocator_3risv2sService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.usFLA2y', 'get_ServiceLocator_UsFLA2yService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.8C5AXya', 'get_ServiceLocator_8C5AXyaService', true],
            'App\\Controller\\UserController:Add' => ['privates', '.service_locator.tXM58lC', 'get_ServiceLocator_TXM58lCService', true],
            'App\\Controller\\UserController:ShowUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.DNF0f.K', 'get_ServiceLocator_DNF0f_KService', true],
            'App\\Controller\\UserController:deletefront' => ['privates', '.service_locator.DNF0f.K', 'get_ServiceLocator_DNF0f_KService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.3risv2s', 'get_ServiceLocator_3risv2sService', true],
            'App\\Controller\\UserController:editfront' => ['privates', '.service_locator.3risv2s', 'get_ServiceLocator_3risv2sService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::Add' => '?',
            'App\\Controller\\UserController::ShowUsers' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::deletefront' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editfront' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:Add' => '?',
            'App\\Controller\\UserController:ShowUsers' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:deletefront' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editfront' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
