<?php

namespace Container0SP7QcW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8C5AXyaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8C5AXya' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8C5AXya'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'authenticationUtils' => '?',
            'doctrine' => '?',
        ]);
    }
}
