vich_uploader:
  db_driver: orm
  mappings:
    reclamation_images:
      uri_prefix: '/uploads/images/reclamation'
      upload_destination: '%kernel.project_dir%/public/uploads/images/reclamation'
      namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
      delete_on_remove: true
      delete_on_update: true
