<?php

namespace ContainerFi5kxkL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Vyv7xSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Vyv7xS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Vyv7xS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authChecker' => ['services', '.container.private.security.authorization_checker', 'get_Container_Private_Security_AuthorizationCheckerService', false],
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
        ], [
            'authChecker' => '?',
            'authenticationUtils' => '?',
        ]);
    }
}
