#index:
#    path: /
#    controller: App\Controller\DefaultController::index
go_to_index:
    path: /go-to-index
    controller: 'App\Controller\ServiceController::index'

show_opp :
    path: /AfficherListeOpp
    controller: 'App\Controller\InvestissementController::show'

edit_inves :
    path: /editInvest/{id}
    controller:  'App\Controller\InvestissementController::edit'

app_afficherinvestissement:
    path: /Afficherinvestissement
    controller :  'App\Controller\InvestissementController::showw'
stripe_webhook:
    path: '/stripe/webhook'
    controller: 'App\Controller\WebhookController::handleStripeWebhook'