#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_home:
    path: /home
    controller: App\Controller\HomeController::index


app_home1:
    path: /home1
    controller: App\Controller\HomeController::index1


app_register:
    path: /register
    controller: App\Controller\RegistrationController::register


app_dashboard:
    path: /dashboard
    controller: App\Controller\HomeController::dashboard



app_login:
    path: /login
    controller: App\Controller\SecurityController::login


app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_afficherlisteusers:
    path: /AfficherListeUsers
    controller: App\Controller\UserController::ShowUsers



app_edit:
    path: /edit/{id}
    controller: App\Controller\UserController::edit


app_editfront:
    path: /editfront/{id}
    controller: App\Controller\UserController::editfront



app_delete:
    path: /delete/{id}
    controller: App\Controller\UserController::delete


app_deletefront:
    path: /deletefront/{id}
    controller: App\Controller\UserController::deletefront




app_AddUser:
    path: /home/Adduser
    controller: App\Controller\UserController::Add  


app_profile:
    path: /profile
    controller: App\Controller\UserController::profile

app_profilefont:
    path: /profilefront
    controller: App\Controller\UserController::profilefront

app_verify_email:
    path: '/verifyemail'
    controller: App\Controller\RegistrationController::verifyEmail
    
 







