<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container17TNuhg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container17TNuhg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container17TNuhg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container17TNuhg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container17TNuhg\App_KernelDevDebugContainer([
    'container.build_hash' => '17TNuhg',
    'container.build_id' => '55b84ade',
    'container.build_time' => 1709856834,
], __DIR__.\DIRECTORY_SEPARATOR.'Container17TNuhg');
