<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFi5kxkL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFi5kxkL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFi5kxkL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFi5kxkL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFi5kxkL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fi5kxkL',
    'container.build_id' => '34e112a0',
    'container.build_time' => 1708466702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFi5kxkL');
